### ISSUE TITLE
How to use config callbacks?

### ISSUE THREAD

**Issue by sqram** [insin/msx#12]
How would i use `config` to call a fuction when an element is rendered?
Here's what i'm trying to achieve using m()

```
m("div, {
  config: function(element, isInitialized, context) {
    if (!isInitialized) doSomething(element)
  }
}
```

**Comment by insin** [comment]
```
<div config={/* Your function here */}/>
```

It's probably nicer if you put the function in your view model, component or module scope and reference it from there.
