### ISSUE TITLE
Typescript JSX support

### ISSUE THREAD

**Issue by dho825** [insin/msx#15]
@insin just wanted to know if there is any idea if Typescript's upcoming (native support for JSX)[http://www.jbrantly.com/typescript-and-jsx/] will also support MSX? 

It seems, from the article, that there are some things very specific to JSX/React going on, but since MSX is takes several things from JSX...I wasn't sure

**Comment by insin** [comment]
I assume there will be some way to configure it to output something other than `React.createElement calls given this quote, but no idea what form that will take:

> JSX in TypeScript was specifically designed to be somewhat agnostic of the consumer. However, React will represent the majority of the usage.

Hopefully it'll be configurable with a dotfile like Babel's JSX output is.
