### ISSUE TITLE
Rewrite support

### ISSUE THREAD

**Issue by sebastiansandqvist** [insin/msx#21]
Are there plans to support the new syntax introduced in mithril v1.x?

**Comment by lugrugzo** [comment]
I don't think so. Looks like the project is abandoned.

**Comment by insin** [comment]
You should be able to use Babel instead for 1.x: https://github.com/lhorie/mithril.js/issues/768#issuecomment-223726915

**Comment by lugrugzo** [comment]
Thanks!
