### ISSUE TITLE
Upgrade to JSX Transformer 0.12

### ISSUE THREAD

**Issue by insin** [insin/msx#7]
As of 0.12, the /`* @jsx */` pragma comment is no longer required, among other things - would be worth updating to pick up that feature alone.

It doesn't look like the new `{...soread}` attributes feature will be usable, as it depends on everyone having an implementation of `Object.assign`/`extend` available, which would have to live on `m`.

**Comment by sdemjanenko** [comment]
I love this.  Thanks so much!
